### ISSUE TITLE
bug: Docker error OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].

### ISSUE THREAD

**Issue by magedhelmy1** [encord-team/encord-active#598]
### Provide environment information

```
(.venv) magedhelmy@Mageds-MacBook-Pro encord-active % encord-active print system-info

/Users/magedhelmy/Desktop/code/playground/encord-active/.venv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
System Information:
        System: Darwin
        Release: 22.2.0
        Machine: arm64
        Processor: arm
        Python: 3.9.6 (default, Oct 18 2022, 12:41:40) 
[Clang 14.0.0 (clang-1400.0.29.202)]

CPU Info:
        Physical cores: 10
        Total cores: 10
        Total CPU Usage: 0.0%

Memory Information:
        Total: 64.00GB
        Available: 20.75GB
        Used: 24.10GB
```

### Describe the bug

I tried to set up the project using Docker as mentioned in the ReadME but I ended up with the message highlighted in the console.log below

### To reproduce

Clone the latest version and run the following command check the console.log

`docker run -it --rm -p 8501:8501 -p 8502:8502 -v `

### Additional information

Here is the console log

```
(.venv) magedhelmy@Mageds-MacBook-Pro encord-active % docker run -it --rm -p 8501:8501 -p 8502:8502 -v ${PWD}:/data encord/encord-active quickstart

Output destination: /data/quickstart
Do you want to re-download the project? [y/N]: y
Downloading sandbox project: 100%|#################################################################| 49.7M/49.7M [00:02<00:00, 23.5MB/s]
Unpacking zip file. May take a bit.
Migrating project at path: /data/quickstart...
Bear with us, this might take a short while...
Migrating project at path: /data/quickstart...

  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.2:8501
  External URL: http://46.15.41.87:8501

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/encord_active/server/start_server.py", line 14, in <module>
    start(Path(sys.argv[1]), reload=("--reload" in sys.argv))
  File "/usr/local/lib/python3.11/site-packages/encord_active/server/start_server.py", line 10, in start
    run("encord_active.server.main:app", reload=reload, host="0.0.0.0", port=8502)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/encord_active/server/main.py", line 7, in <module>
    from encord_active.lib.model_predictions.reader import read_prediction_files
  File "/usr/local/lib/python3.11/site-packages/encord_active/lib/model_predictions/reader.py", line 10, in <module>
    from encord_active.lib.common.utils import load_json
  File "/usr/local/lib/python3.11/site-packages/encord_active/lib/common/utils.py", line 18, in <module>
    from shapely.geometry import Polygon
  File "/usr/local/lib/python3.11/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/usr/local/lib/python3.11/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/usr/local/lib/python3.11/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/usr/local/lib/python3.11/site-packages/shapely/geos.py", line 100, in <module>
    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/shapely/geos.py", line 54, in load_dll
    raise OSError(
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
2023-08-15 12:58:56.813 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/usr/local/lib/python3.11/site-packages/encord_active/app/streamlit_entrypoint.py", line 14, in <module>
    from encord_active.app.auth.jwt import auth
  File "/usr/local/lib/python3.11/site-packages/encord_active/app/auth/jwt.py", line 6, in <module>
    from encord_active.app.common.state_hooks import UseState
  File "/usr/local/lib/python3.11/site-packages/encord_active/app/common/state_hooks.py", line 6, in <module>
    from encord_active.app.common.state import StateKey
  File "/usr/local/lib/python3.11/site-packages/encord_active/app/common/state.py", line 10, in <module>
    from encord_active.lib.common.filtering import Filters
  File "/usr/local/lib/python3.11/site-packages/encord_active/lib/common/filtering.py", line 9, in <module>
    from encord_active.lib.model_predictions.types import PredictionsFilters
  File "/usr/local/lib/python3.11/site-packages/encord_active/lib/model_predictions/types.py", line 12, in <module>
    from encord_active.lib.model_predictions.writer import MainPredictionType
  File "/usr/local/lib/python3.11/site-packages/encord_active/lib/model_predictions/writer.py", line 19, in <module>
    from encord_active.lib.common.utils import RLEData, binary_mask_to_rle, rle_iou
  File "/usr/local/lib/python3.11/site-packages/encord_active/lib/common/utils.py", line 18, in <module>
    from shapely.geometry import Polygon
  File "/usr/local/lib/python3.11/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/usr/local/lib/python3.11/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/usr/local/lib/python3.11/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/usr/local/lib/python3.11/site-packages/shapely/geos.py", line 100, in <module>
    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/shapely/geos.py", line 54, in load_dll
    raise OSError(
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
```

**Comment by frederik-encord** [comment]
With #631, this issue is fixed.
